// Calm, light tone system. Keys are kept stable (brand/mint/flamingo/sun/sky2/lime)
// so existing references map cleanly onto the new green-centric palette.
// Literal class strings so Tailwind's JIT keeps them.
export const TONES = {
  brand: {
    text: 'text-brand-600',
    bgSoft: 'bg-brand-50',
    border: 'border-brand-200',
    ring: 'ring-brand-500/20',
    dot: 'bg-brand-500',
    grad: 'from-brand-400 to-brand-600',
    gradText: 'from-brand-500 to-brand-700',
    solid: 'bg-brand-500',
    glow: 'shadow-lift',
  },
  mint: {
    text: 'text-mint-500',
    bgSoft: 'bg-mint-50',
    border: 'border-mint-100',
    ring: 'ring-mint-500/20',
    dot: 'bg-mint-500',
    grad: 'from-mint-400 to-mint-500',
    gradText: 'from-mint-400 to-mint-500',
    solid: 'bg-mint-500',
    glow: 'shadow-soft',
  },
  flamingo: {
    text: 'text-flamingo-500',
    bgSoft: 'bg-flamingo-50',
    border: 'border-flamingo-100',
    ring: 'ring-flamingo-500/20',
    dot: 'bg-flamingo-400',
    grad: 'from-flamingo-400 to-flamingo-500',
    gradText: 'from-flamingo-400 to-flamingo-500',
    solid: 'bg-flamingo-400',
    glow: 'shadow-soft',
  },
  sun: {
    text: 'text-sun-500',
    bgSoft: 'bg-sun-50',
    border: 'border-sun-100',
    ring: 'ring-sun-500/20',
    dot: 'bg-sun-400',
    grad: 'from-sun-400 to-sun-500',
    gradText: 'from-sun-400 to-sun-500',
    solid: 'bg-sun-400',
    glow: 'shadow-soft',
  },
  gold: {
    text: 'text-gold-500',
    bgSoft: 'bg-gold-50',
    border: 'border-gold-100',
    ring: 'ring-gold-500/20',
    dot: 'bg-gold-400',
    grad: 'from-gold-400 to-gold-500',
    gradText: 'from-gold-400 to-gold-500',
    solid: 'bg-gold-400',
    glow: 'shadow-soft',
  },
  sky2: {
    text: 'text-sky2-500',
    bgSoft: 'bg-sky2-50',
    border: 'border-sky2-100',
    ring: 'ring-sky2-500/20',
    dot: 'bg-sky2-400',
    grad: 'from-sky2-400 to-sky2-500',
    gradText: 'from-sky2-400 to-sky2-500',
    solid: 'bg-sky2-400',
    glow: 'shadow-soft',
  },
  lime: {
    text: 'text-lime-500',
    bgSoft: 'bg-lime-50',
    border: 'border-lime-100',
    ring: 'ring-lime-500/20',
    dot: 'bg-lime-400',
    grad: 'from-lime-400 to-lime-500',
    gradText: 'from-lime-400 to-lime-500',
    solid: 'bg-lime-400',
    glow: 'shadow-soft',
  },
}

export const tone = (t) => TONES[t] || TONES.brand
